entry-pipeline-traces:
  source:
    otlp_traces:
      ssl: false
      port: 21890
  sink:
    - stdout:

entry-pipeline-metrics:
  source:
    otlp_metrics:
      ssl: false
      port: 21891
  sink:
    - stdout:

entry-pipeline-logs:
  source:
    otlp_logs:
      ssl: false
      port: 21892
  sink:
    - stdout:
