{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "postyfox.fullname" . }}
  labels: {{- include "postyfox.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.coreApiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: {{ include "postyfox.fullname" . }}-core-api, port: { number: 8080 } } }
    - host: {{ .Values.ingress.postApiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: {{ include "postyfox.fullname" . }}-post-api, port: { number: 8080 } } }
{{- end }}
