{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postyfox.secretName" . }}
  labels: {{- include "postyfox.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Postgres: {{ .Values.secrets.postgresConnection | quote }}
  Secrets__BitWarden__ApiKey: {{ .Values.secrets.bitwardenApiKey | quote }}
  Secrets__BitWarden__ClientId: {{ .Values.secrets.bitwardenClientId | quote }}
  Secrets__BitWarden__ClientSecret: {{ .Values.secrets.bitwardenClientSecret | quote }}
  NodeConnectors__InternalToken: {{ .Values.secrets.internalToken | quote }}
  INTERNAL_TOKEN: {{ .Values.secrets.internalToken | quote }}
  ObjectStore__AccessKey: {{ .Values.secrets.objectStoreAccessKey | quote }}
  ObjectStore__SecretKey: {{ .Values.secrets.objectStoreSecretKey | quote }}
  RabbitMq__Password: {{ .Values.secrets.rabbitMqPassword | quote }}
{{- end }}
