
name: 'Deploy Core'

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: 'Environment to Target'     
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    # environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Login using az login and a service principal, allowing Terraform to access the account
    - name: Azure Login
      shell: pwsh
      run: |
        az login --service-principal -u $env:ARM_CLIENT_ID -p $env:ARM_CLIENT_SECRET --tenant $env:ARM_TENANT_ID
      env:
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1

    - name: Tofu Init
      run: tofu init -upgrade -backend-config="key=${{inputs.targetEnvironment}}.tfstate" -reconfigure
      working-directory: /home/runner/work/postyfox-core/postyfox-core/terraform
      env:
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

    - name: Tofu Plan
      run: "tofu plan --var-file=./envs/${{inputs.targetEnvironment}}.tfvars"
      working-directory: /home/runner/work/postyfox-core/postyfox-core/terraform
      env:
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

    - name: Tofu Apply
      run: "tofu apply -auto-approve --var-file=./envs/${{inputs.targetEnvironment}}.tfvars"
      working-directory: /home/runner/work/postyfox-core/postyfox-core/terraform
      env:
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}

  codebuild:
    name: 'Code Build'
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.upload-dotnet-fa.outputs.artifact-id }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Build the .NET core Function App
    - name: Setup .NET Core 8.x
      uses: actions/setup-dotnet@v4
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '8.x'

    - name: Install dotnet Core dependencies
      run: dotnet restore
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-NetCore

    - name: Build dotnet Core Function App
      run: dotnet build -c Release -v d
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-NetCore

    - name: Publish dotnet Core Function App
      run: dotnet publish -v d -o /home/runner/work/output/dotnet-fa
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-NetCore

    - uses: actions/upload-artifact@v4
      name: Upload DotNet Function App Artifact
      id: upload-dotnet-fa
      with:
        name: dotnet-fa
        path: /home/runner/work/output/dotnet-fa

    - name: Setup Node v20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: npm install
      run: npm install 
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-TypeScript

    - name: npm build
      run: npm run build
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-TypeScript

    - uses: actions/upload-artifact@v4
      name: Upload NodeJS Function App Artifact
      id: upload-nodejs-fa
      with:
        name: nodejs-fa
        path: /home/runner/work/postyfox-core/postyfox-core/PostyFox-TypeScript

  deploy:
    needs: [terraform, codebuild]
    name: 'Code Deployment'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Upload Dot Net Function App'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: postyfox-func-app-dotnet-${{ inputs.targetEnvironment }}
          package: '/home/runner/work/postyfox-core/postyfox-core/dotnet-fa'

      - name: 'Upload NodeJS Function App'
        uses: Azure/functions-action@v1
        id: nfa
        with:
          app-name: postyfox-func-app-nodejs-${{ inputs.targetEnvironment }}
          package: '/home/runner/work/postyfox-core/postyfox-core/nodejs-fa'          