
name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      targetEnvironment:
        description: 'Environment to Target'     
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    # environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Login using az login and a service principal, allowing Terraform to access the account
    - name: Azure Login
      shell: pwsh
      run: |
        az login --service-principal -u $env:ARM_CLIENT_ID -p $env:ARM_CLIENT_SECRET --tenant $env:ARM_TENANT_ID

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: /home/runner/work/postyfox-core/postyfox-core/terraform

    - name: Terraform Plan
      run: terraform plan -var environment="${{inputs.targetEnvironment}}"
      working-directory: /home/runner/work/postyfox-core/postyfox-core/terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var environment="${{inputs.targetEnvironment}}"
      working-directory: /home/runner/work/postyfox-core/postyfox-core/terraform

  codebuild:
    name: 'Code Build'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Build the .NET core Function App
    - name: Setup .NET Core 7.x
      uses: actions/setup-dotnet@v3
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '7.x'

    - name: Install dotnet Core dependencies
      run: dotnet restore
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-NetCore

    - name: Build dotnet Core Function App
      run: dotnet build
      working-directory: /home/runner/work/postyfox-core/postyfox-core/PostyFox-NetCore

  # deploy:
  #   name: 'Code Deployment'
  #   runs-on: ubuntu-latest

  #   steps:

    # Deploy .NET core Function App